upstream student_web_upstream {
  server student-web:8080;
  keepalive 16;
}

upstream counselor_web_upstream {
  server counselor-web:8080;
  keepalive 16;
}

upstream api_upstream {
  server api:4000;
  keepalive 32;
}
