server {
  listen 80;
  server_name counselor.konkourix.ir;

  location = /health/live {
    access_log off;
    proxy_pass http://counselor_web_upstream;
  }

  location ^~ /assets/ {
    proxy_pass http://counselor_web_upstream;
    expires 1y;
  }

  location / {
    proxy_pass http://counselor_web_upstream;
    expires -1;
  }
}
